@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb pageTitle="Courses"><x-slot:actions>@can('courses.create')<a href="{{ route(\App\Support\PortalRoute::name('courses.create')) }}" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white">Create course</a>@endcan</x-slot:actions></x-common.page-breadcrumb>
<x-common.component-card title="Course catalog" desc="Build curricula, publish learning, and monitor enrollment.">
    <form method="GET" class="grid gap-3 md:grid-cols-[1fr_180px_220px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search courses" class="h-11 rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:text-white"><x-form.select name="status" :options="['draft' => 'Draft', 'published' => 'Published', 'archived' => 'Archived']" :value="request('status')" placeholder="All statuses" /><x-form.select name="category_id" :options="$categories" :value="request('category_id')" placeholder="All categories" /><button class="h-11 rounded-lg border border-gray-300 px-4 text-sm dark:border-gray-700 dark:text-white">Filter</button></form>
    <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-4">@forelse($courses as $course)<article @can('courses.show') role="link" tabindex="0" @click="if (!$event.target.closest('a, button, form')) window.location.href = @js(route(\App\Support\PortalRoute::name('courses.show'), $course))" @keydown.enter.prevent="window.location.href = @js(route(\App\Support\PortalRoute::name('courses.show'), $course))" @endcan class="group w-full max-w-[600px] overflow-hidden rounded-2xl border border-gray-200 bg-white transition-all duration-300 hover:-translate-y-1 hover:border-brand-200 hover:shadow-theme-lg dark:border-gray-800 dark:bg-white/[0.03] dark:hover:border-brand-500/40 @can('courses.show') cursor-pointer @endcan">
        <div class="aspect-[3/2] w-full overflow-hidden bg-brand-50 dark:bg-brand-500/10">
            @if($course->thumbnail_path)<img src="{{ Storage::disk('public')->url($course->thumbnail_path) }}" alt="{{ $course->title }} thumbnail" class="h-full w-full object-cover transition-transform duration-500 ease-out group-hover:scale-105">@else<div class="flex h-full w-full items-center justify-center text-5xl font-semibold text-brand-500 transition-transform duration-500 ease-out group-hover:scale-105">{{ Str::upper(Str::substr($course->title, 0, 1)) }}</div>@endif
        </div>
        <div class="space-y-5 p-5"><div class="flex items-start justify-between gap-3"><h3 class="cursor-pointer text-xl font-semibold text-gray-800 transition-colors duration-200 group-hover:text-brand-600 dark:text-white dark:group-hover:text-brand-400">{{ $course->title }}</h3><x-ui.badge :color="$course->status->value === 'published' ? 'success' : ($course->status->value === 'archived' ? 'light' : 'warning')">{{ $course->status->value }}</x-ui.badge></div>
        <div class="flex items-center justify-between gap-3 border-t border-gray-100 pt-4 dark:border-gray-800"><p class="text-xs text-gray-500">Created {{ $course->created_at?->format('M j, Y') ?? '—' }} <span class="mx-1 text-gray-300 dark:text-gray-600">|</span> {{ $course->instructor?->name ?? 'Unassigned' }}</p>@can('courses.show')<a href="{{ route(\App\Support\PortalRoute::name('courses.show'), $course) }}" class="inline-flex shrink-0 items-center rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-brand-600 transition-colors hover:border-brand-500 hover:bg-brand-50 dark:border-gray-700 dark:text-brand-400 dark:hover:bg-brand-500/10">Open</a>@endcan</div></div>
    </article>@empty<p class="col-span-full py-10 text-center text-sm text-gray-500">No courses found.</p>@endforelse</div>{{ $courses->links() }}
</x-common.component-card>
@endsection
