@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb pageTitle="Courses"><x-slot:actions>@can('courses.create')<a href="{{ route(\App\Support\PortalRoute::name('courses.create')) }}" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white">Create course</a>@endcan</x-slot:actions></x-common.page-breadcrumb>
<x-common.component-card title="Course catalog" desc="Build curricula, publish learning, and monitor enrollment.">
    <form method="GET" class="grid gap-3 md:grid-cols-[1fr_180px_220px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search courses" class="h-11 rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:text-white"><x-form.select name="status" :options="['draft' => 'Draft', 'published' => 'Published', 'archived' => 'Archived']" :value="request('status')" placeholder="All statuses" /><x-form.select name="category_id" :options="$categories" :value="request('category_id')" placeholder="All categories" /><button class="h-11 rounded-lg border border-gray-300 px-4 text-sm dark:border-gray-700 dark:text-white">Filter</button></form>
    <div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($courses as $course)<article class="overflow-hidden rounded-xl border border-gray-200 dark:border-gray-800">
        @if($course->thumbnail_path)<img src="{{ Storage::disk('public')->url($course->thumbnail_path) }}" alt="" class="h-36 w-full object-cover">@else<div class="flex h-36 items-center justify-center bg-brand-50 text-3xl font-semibold text-brand-500 dark:bg-brand-500/10">{{ Str::upper(Str::substr($course->title, 0, 1)) }}</div>@endif
        <div class="space-y-3 p-5"><div class="flex items-start justify-between gap-2"><h3 class="font-semibold text-gray-800 dark:text-white">{{ $course->title }}</h3><x-ui.badge :color="$course->status->value === 'published' ? 'success' : ($course->status->value === 'archived' ? 'light' : 'warning')">{{ $course->status->value }}</x-ui.badge></div>
        <p class="text-sm text-gray-500">{{ Str::limit($course->short_description, 110) }}</p><div class="flex justify-between text-xs text-gray-500"><span>{{ $course->modules_count }} modules</span><span>{{ $course->enrollments_count }} trainees</span></div><p class="text-xs text-gray-500">Instructor: {{ $course->instructor?->name ?? 'Unassigned' }}</p>
        @can('courses.show')<a href="{{ route(\App\Support\PortalRoute::name('courses.show'), $course) }}" class="inline-flex rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-brand-500 dark:border-gray-700">Open course</a>@endcan</div>
    </article>@empty<p class="col-span-full py-10 text-center text-sm text-gray-500">No courses found.</p>@endforelse</div>{{ $courses->links() }}
</x-common.component-card>
@endsection
