@extends('layouts.app')
@section('content')
<div x-data="{ remaining: {{ max(0, now()->diffInSeconds($attempt->expires_at, false)) }}, timer: null }" x-init="timer = setInterval(() => { if (remaining > 0) remaining--; else { clearInterval(timer); $refs.testForm.submit(); } }, 1000)" class="mx-auto max-w-4xl">
<x-common.page-breadcrumb :pageTitle="$attempt->assessment->title"><x-slot:actions><div class="rounded-lg bg-warning-50 px-4 py-2 text-sm font-semibold text-warning-700 dark:bg-warning-500/10"><span x-text="`${Math.floor(remaining / 60)}:${String(remaining % 60).padStart(2, '0')}`"></span> remaining</div></x-slot:actions></x-common.page-breadcrumb>
<x-common.component-card :title="'Attempt '.$attempt->attempt_number" :desc="$attempt->assessment->instructions ?? 'Answer every question, then submit for automatic grading.'"><form x-ref="testForm" method="POST" action="{{ route('learning.assessments.attempts.submit', $attempt) }}" class="space-y-8">@csrf
    @foreach($attempt->assessment->questions as $question)<fieldset class="rounded-xl border border-gray-200 p-5 dark:border-gray-800"><legend class="px-2 font-medium text-gray-800 dark:text-white">{{ $loop->iteration }}. {{ $question->prompt }} <span class="text-xs font-normal text-gray-500">({{ $question->marks }} marks)</span></legend><div class="mt-3 space-y-2">@foreach($question->options as $option)<label class="flex cursor-pointer items-center gap-3 rounded-lg border border-gray-200 px-4 py-3 text-sm text-gray-700 hover:border-brand-300 dark:border-gray-800 dark:text-gray-300"><input type="{{ $question->type === \App\Enums\QuestionType::MultipleChoice ? 'checkbox' : 'radio' }}" name="answers[{{ $question->id }}]{{ $question->type === \App\Enums\QuestionType::MultipleChoice ? '[]' : '' }}" value="{{ $option->id }}" class="h-4 w-4 border-gray-300 text-brand-500">{{ $option->option_text }}</label>@endforeach</div></fieldset>@endforeach
    <div class="flex justify-end"><button class="rounded-lg bg-brand-500 px-6 py-3 text-sm font-medium text-white" onclick="return confirm('Submit this attempt for grading?')">Submit assessment</button></div>
</form></x-common.component-card></div>
@endsection
