@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb :pageTitle="$title"><x-slot:actions>@can('fiscal-years.create')<a href="{{ route('super-admin.fiscal-years.create') }}" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white">Create fiscal year</a>@endcan</x-slot:actions></x-common.page-breadcrumb>
<x-common.component-card title="Fiscal-year management" desc="Define attendance thresholds and credit values for each claim period.">
    <form method="GET" class="mb-5 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><x-form.input name="search" label="Search" :value="request('search')" placeholder="Fiscal year name" /><x-form.select name="status" label="Status" :options="['draft' => 'Draft', 'active' => 'Active', 'closed' => 'Closed']" :value="request('status')" placeholder="All statuses" /><div class="flex items-end gap-2"><button class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white">Filter</button><a href="{{ route('super-admin.fiscal-years.index') }}" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm dark:border-gray-700 dark:text-white">Clear</a></div></form>
    <div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800"><thead><tr class="text-left text-xs uppercase tracking-wide text-gray-500"><th class="px-4 py-3">Name</th><th class="px-4 py-3">Period</th><th class="px-4 py-3">Attendance rule</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($fiscalYears as $fiscalYear)<tr><td class="px-4 py-4 font-medium text-gray-800 dark:text-white">{{ $fiscalYear->name }}</td><td class="px-4 py-4 text-sm text-gray-500">{{ $fiscalYear->starts_on->format('M d, Y') }} – {{ $fiscalYear->ends_on->format('M d, Y') }}</td><td class="px-4 py-4 text-sm text-gray-500">{{ $fiscalYear->attendance_threshold_days }} days · {{ number_format($fiscalYear->attendance_credit_points, 2) }} credits</td><td class="px-4 py-4"><x-ui.badge :color="$fiscalYear->status->value === 'active' ? 'success' : ($fiscalYear->status->value === 'closed' ? 'dark' : 'warning')">{{ $fiscalYear->status->label() }}</x-ui.badge></td><td class="px-4 py-4"><div class="flex justify-end gap-2">@can('fiscal-years.show')<a href="{{ route('super-admin.fiscal-years.show', $fiscalYear) }}" class="rounded border border-gray-300 px-2 py-1 text-xs dark:border-gray-700 dark:text-white">View</a>@endcan @can('fiscal-years.edit')@if($fiscalYear->status->value === 'draft')<a href="{{ route('super-admin.fiscal-years.edit', $fiscalYear) }}" class="rounded border border-gray-300 px-2 py-1 text-xs dark:border-gray-700 dark:text-white">Edit</a>@endif<form method="POST" action="{{ route('super-admin.fiscal-years.status', $fiscalYear) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $fiscalYear->status->value === 'draft' ? 'active' : 'closed' }}"><button class="rounded border border-brand-300 px-2 py-1 text-xs text-brand-600">{{ $fiscalYear->status->value === 'draft' ? 'Activate' : 'Close' }}</button></form>@endcan @can('fiscal-years.delete')@if($fiscalYear->status->value === 'draft')<form method="POST" action="{{ route('super-admin.fiscal-years.destroy', $fiscalYear) }}" onsubmit="return confirm('Delete this unused fiscal year?')">@csrf @method('DELETE')<button class="rounded bg-error-50 px-2 py-1 text-xs text-error-600">Delete</button></form>@endif @endcan</div></td></tr>@empty<tr><td colspan="5" class="px-4 py-8 text-center text-sm text-gray-500">No fiscal years found.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-5">{{ $fiscalYears->links() }}</div>
</x-common.component-card>
@endsection
