@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb pageTitle="Tests & Quizzes"><x-slot:actions>@can('assessments.create')<a href="{{ route(\App\Support\PortalRoute::name('assessments.create')) }}" class="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white">Create quiz</a>@endcan</x-slot:actions></x-common.page-breadcrumb>
<x-common.component-card title="Quiz management" desc="Quizzes are independent tests assigned directly to trainees.">
    <form method="GET" class="grid gap-3 sm:grid-cols-[1fr_180px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search quizzes" class="h-11 rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:text-white"><x-form.select name="status" :options="['draft' => 'Draft', 'published' => 'Published', 'closed' => 'Closed']" :value="request('status')" placeholder="All statuses" /><button class="h-11 rounded-lg border border-gray-300 px-4 text-sm dark:border-gray-700 dark:text-white">Filter</button></form>
    <div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800"><thead><tr class="text-left text-xs uppercase text-gray-500"><th class="px-2 py-3">S.N.</th><th class="px-4 py-3">Quiz</th><th class="px-4 py-3">Owner</th><th class="px-4 py-3">Questions</th><th class="px-4 py-3">Attempts</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
    @forelse($assessments as $assessment)<tr><td class="px-2 py-4 text-sm text-gray-500">{{ $assessments->firstItem() + $loop->index }}</td><td class="px-4 py-4"><p class="font-medium text-gray-800 dark:text-white">{{ $assessment->title }}</p><p class="text-xs text-gray-500">{{ $assessment->duration_minutes }} min · Pass {{ $assessment->passing_percentage }}%</p></td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $assessment->creator?->name ?? 'Former user' }}</td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $assessment->questions_count }}</td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $assessment->attempts_count }}</td><td class="px-4 py-4"><x-ui.badge :color="$assessment->status->value === 'published' ? 'success' : ($assessment->status->value === 'closed' ? 'light' : 'warning')">{{ $assessment->status->value }}</x-ui.badge></td><td class="px-4 py-4"><div class="flex justify-end gap-2">@can('assessments.show')<a href="{{ route(\App\Support\PortalRoute::name('assessments.show'), $assessment) }}" class="rounded-lg border border-gray-300 px-3 py-2 text-xs text-brand-500 dark:border-gray-700">Open</a>@endcan @can('assessments.edit')<a href="{{ route(\App\Support\PortalRoute::name('assessments.edit'), $assessment) }}" class="rounded-lg border border-gray-300 px-3 py-2 text-xs dark:border-gray-700 dark:text-white">Edit</a>@endcan</div></td></tr>
    @empty<tr><td colspan="7" class="px-4 py-10 text-center text-sm text-gray-500">No quizzes found.</td></tr>@endforelse</tbody></table></div>{{ $assessments->links() }}
</x-common.component-card>
@endsection
