@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb pageTitle="Enrollments" />
<div class="grid gap-6 xl:grid-cols-[360px_1fr]">
    @can('enrollments.create')<x-common.component-card title="Assign course" desc="Assign one published course to one or more trainees."><form method="POST" action="{{ route(\App\Support\PortalRoute::name('enrollments.store')) }}" class="space-y-5">@csrf <x-form.searchable-select name="course_id" label="Published course" :options="$courses" required /><x-form.multiselect name="trainees[]" label="Trainees" :options="$trainees" help="Direct assignment activates learning immediately and supersedes a pending request." /><button class="w-full rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white">Assign course</button></form></x-common.component-card>@endcan
    <x-common.component-card title="Enrollment records" desc="Track active, completed, and cancelled assignments.">
        <form method="GET" class="grid gap-3 md:grid-cols-[1fr_220px_160px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search trainee" class="h-11 rounded-lg border border-gray-300 bg-transparent px-4 text-sm dark:border-gray-700 dark:text-white"><x-form.select name="course_id" :options="$courses" :value="request('course_id')" placeholder="All courses" /><x-form.select name="status" :options="['active' => 'Active', 'completed' => 'Completed', 'cancelled' => 'Cancelled']" :value="request('status')" placeholder="All statuses" /><button class="h-11 rounded-lg border border-gray-300 px-4 text-sm dark:border-gray-700 dark:text-white">Filter</button></form>
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800"><thead><tr class="text-left text-xs uppercase text-gray-500"><th class="px-2 py-3">S.N.</th><th class="px-4 py-3">Trainee</th><th class="px-4 py-3">Course</th><th class="px-4 py-3">Progress</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">
            @forelse($enrollments as $enrollment)<tr><td class="px-2 py-4 text-sm text-gray-500">{{ $enrollments->firstItem() + $loop->index }}</td><td class="px-4 py-4"><p class="font-medium text-gray-800 dark:text-white">{{ $enrollment->trainee->name }}</p><p class="text-xs text-gray-500">{{ $enrollment->trainee->email }}</p></td><td class="px-4 py-4 text-sm text-gray-700 dark:text-gray-300">{{ $enrollment->course->title }}</td><td class="px-4 py-4"><div class="w-28 rounded-full bg-gray-100 dark:bg-gray-800"><div class="h-2 rounded-full bg-brand-500" style="width: {{ $enrollment->progress_percentage }}%"></div></div><span class="text-xs text-gray-500">{{ $enrollment->progress_percentage }}%</span></td><td class="px-4 py-4"><x-ui.badge :color="$enrollment->status->value === 'completed' ? 'success' : ($enrollment->status->value === 'cancelled' ? 'error' : ($enrollment->status->value === 'pending' ? 'warning' : 'primary'))">{{ $enrollment->status->value }}</x-ui.badge></td><td class="px-4 py-4 text-right">@can('enrollments.delete') @if(in_array($enrollment->status->value, ['active', 'completed'], true))<form method="POST" action="{{ route(\App\Support\PortalRoute::name('enrollments.destroy'), $enrollment) }}" onsubmit="return confirm('Cancel this enrollment?')">@csrf @method('DELETE')<button class="rounded-lg bg-error-50 px-3 py-2 text-xs text-error-600">Cancel</button></form>@endif @endcan</td></tr>
            @empty<tr><td colspan="6" class="px-4 py-10 text-center text-sm text-gray-500">No enrollment records found.</td></tr>@endforelse
        </tbody></table></div>{{ $enrollments->links() }}
    </x-common.component-card>
</div>
@endsection
