@extends('layouts.app')
@section('content')
<x-common.page-breadcrumb pageTitle="LMS Reports" />
<div class="mb-6 grid gap-4 sm:grid-cols-3">@foreach(['Completion rate' => $summary['completion_rate'].'%', 'Pass rate' => $summary['pass_rate'].'%', 'Average progress' => $summary['average_progress'].'%'] as $label => $value)<div class="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm text-gray-500">{{ $label }}</p><p class="mt-2 text-3xl font-bold text-gray-800 dark:text-white">{{ $value }}</p></div>@endforeach</div>
<div class="space-y-6">
<x-common.component-card title="Course report"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800"><thead><tr class="text-left text-xs uppercase text-gray-500"><th class="px-4 py-3">Course</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Enrolled</th><th class="px-4 py-3">Completed</th><th class="px-4 py-3">Completion</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($courses as $course)<tr><td class="px-4 py-4 font-medium text-gray-800 dark:text-white">{{ $course->title }}</td><td class="px-4 py-4"><x-ui.badge>{{ $course->status->value }}</x-ui.badge></td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $course->enrollments_count }}</td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $course->completed_count }}</td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $course->enrollments_count ? round($course->completed_count / $course->enrollments_count * 100, 1) : 0 }}%</td></tr>@empty<tr><td colspan="5" class="px-4 py-8 text-center text-sm text-gray-500">No courses.</td></tr>@endforelse</tbody></table></div></x-common.component-card>
<div class="grid gap-6 xl:grid-cols-2"><x-common.component-card title="Trainee report"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800"><thead><tr class="text-left text-xs uppercase text-gray-500"><th class="px-4 py-3">Trainee</th><th class="px-4 py-3">Enrolled</th><th class="px-4 py-3">Completed</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($trainees as $trainee)<tr><td class="px-4 py-4"><p class="font-medium text-gray-800 dark:text-white">{{ $trainee->name }}</p><p class="text-xs text-gray-500">{{ $trainee->email }}</p></td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $trainee->enrollments_count }}</td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $trainee->completed_count }}</td></tr>@empty<tr><td colspan="3" class="px-4 py-8 text-center text-sm text-gray-500">No trainees.</td></tr>@endforelse</tbody></table></div></x-common.component-card>
<x-common.component-card title="Assessment report"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 dark:divide-gray-800"><thead><tr class="text-left text-xs uppercase text-gray-500"><th class="px-4 py-3">Assessment</th><th class="px-4 py-3">Attempts</th><th class="px-4 py-3">Pass / Fail</th><th class="px-4 py-3">Average</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800">@forelse($assessments as $assessment)<tr><td class="px-4 py-4 font-medium text-gray-800 dark:text-white">{{ $assessment->title }}</td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $assessment->attempts_count }}</td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $assessment->pass_count }} / {{ $assessment->fail_count }}</td><td class="px-4 py-4 text-sm text-gray-600 dark:text-gray-300">{{ $assessment->average_score ?? 0 }}%</td></tr>@empty<tr><td colspan="4" class="px-4 py-8 text-center text-sm text-gray-500">No assessments.</td></tr>@endforelse</tbody></table></div></x-common.component-card></div>
</div>
@endsection
